### ISSUE TITLE
Google Scholar User Profile

### ISSUE THREAD

**Issue by kcrooks1006** [jastiso/citation_bias_ext#4]
In Google Scholar, when a search for a person is conducted and the person in question has their own Google Scholar account, the "User Profiles" section considers the first and last author to be Mike Kuniavsky (gender: male 99%). Error is found when there is only one option (see search for Jennifer Stiso below) or if there are several authors with a similar name that have a profile (see search for Matthew Sutherland).

![Scholar_Mike3](https://user-images.githubusercontent.com/53243182/85027867-68aab100-b148-11ea-9fdc-cda5782b55a2.PNG)

![Scholar_Mike2](https://user-images.githubusercontent.com/53243182/85027869-69434780-b148-11ea-89a3-30e6979bd4f7.PNG)

**Comment by jastiso** [comment]
Added extra filtering by element ID, so this should no longer be an issue. Changes pushed to repo, resolving now :)
